@echo off
echo Starting NBA Live Odds...

echo Starting Docker...
docker compose up -d

echo Starting poller in new window...
start "Poller" cmd /k "cd backend && venv\Scripts\activate && python -m app.services.poller"

echo Starting FastAPI in new window...
start "FastAPI" cmd /k "cd backend && venv\Scripts\activate && python -m uvicorn app.main:app --reload"

echo Starting React in new window...
start "React" cmd /k "cd frontend && npm run dev"

echo Starting ngrok...
start "ngrok" cmd /k "ngrok http --domain=expand-landlord-onscreen.ngrok-free.dev 8000"

echo All services starting...
pause